name: "units-test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.dev-test.outputs.sha }}
      ref: ${{ steps.dev-test.outputs.ref }}
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: ./
      id: dev-test
      with:
        environment: dev
        token: ${{ secrets.GITHUB_TOKEN  }}

    - name: echo time
      run: echo "${{ steps.dev-test.outputs.sha }}"

    - name: echo ref
      run: echo "${{ steps.dev-test.outputs.ref }}"

    - uses: ./
      id: prod-test
      with:
        environment: prod
        token: ${{ secrets.GITHUB_TOKEN  }}

    - name: echo time
      run: echo "${{ steps.prod-test.outputs.sha }}"
    - name: echo ref
      run: echo "${{ steps.prod-test.outputs.ref }}"

  get-outputs:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - run: |
        echo ${{ needs.test.outputs.sha }}
        echo ${{ needs.test.outputs.ref }}