name: "units-test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: ./
      id: dev-test
      with:
        environment: dev
        token: ${{ secrets.GITHUB_TOKEN  }}

    - run: echo "${{ steps.dev-test.outputs.time }}"
    - run: echo "${{ steps.dev-test.outputs.ref }}"

    - uses: ./
      id: prod-test
      with:
        environment: prod
        token: ${{ secrets.GITHUB_TOKEN  }}

    - run: echo "${{ steps.prod-test.outputs.time }}"
    - run: echo "${{ steps.prod-test.outputs.ref }}
"